Support Ubuntu 24.04 (#15)
* feat(find-driver-version): support multiple distro

* feat(ckmb): support different ubuntu distro

* fix(ckmb): switch to python3-minimal for u24

* fix(repository): update apt mirror

diff --git a/dd_scripts/nvidia-driver b/dd_scripts/nvidia-driver
--- a/dd_scripts/nvidia-driver
+++ b/dd_scripts/nvidia-driver
@@ -4,21 +4,55 @@
 set -eu
 
 KERNEL_VERSION=$(uname -r)
-OPEN_KERNEL_MODULES_ENABLED="${OPEN_KERNEL_MODULES_ENABLED:-false}"
 RUN_DIR=/run/nvidia
 PID_FILE=${RUN_DIR}/${0##*/}.pid
-DRIVER_BRANCH=${DRIVER_BRANCH:?"Missing driver version"}
+DRIVER_BRANCH=${DRIVER_BRANCH:?"Missing driver branch"}
+DRIVER_VERSION=${DRIVER_VERSION:?"Missing driver version"}
+MODULES_VERSION=${MODULES_VERSION:?"Missing modules version"}
+FULL_DRIVER_VERSION=${FULL_DRIVER_VERSION:?"Missing full driver version"}
 GPU_DIRECT_RDMA_ENABLED="${GPU_DIRECT_RDMA_ENABLED:-false}"
 USE_HOST_MOFED="${USE_HOST_MOFED:-false}"
 NVIDIA_MODULE_PARAMS=()
 NVIDIA_UVM_MODULE_PARAMS=()
 NVIDIA_MODESET_MODULE_PARAMS=()
 NVIDIA_PEERMEM_MODULE_PARAMS=()
+TARGETARCH=${TARGETARCH:?"Missing TARGETARCH env"}
+KERNEL_MODULE_TYPE=${KERNEL_MODULE_TYPE:-auto}
+MODPROBE_CONFIG_DIR="/etc/modprobe.d"
+
+source "$(dirname "$0")/grid-driver"
+
+fabricmanager_install() {
+    apt-get install -y --no-install-recommends nvidia-fabricmanager-${DRIVER_BRANCH}=${FULL_DRIVER_VERSION}
+}
+
+nscq_install() {
+    apt-get install -y --no-install-recommends libnvidia-nscq-${DRIVER_BRANCH}=${FULL_DRIVER_VERSION}
+}
+
+imex_install() {
+    apt-get install -y --no-install-recommends nvidia-imex-${DRIVER_BRANCH}=${FULL_DRIVER_VERSION}
+}
+
+nvlink5_pkgs_install() {
+    apt-get install -y --no-install-recommends infiniband-diags nvlsm
+}
+
+# libnvsdm packages are not available for arm64
+nvsdm_install() {
+    if [ "$TARGETARCH" = "amd64" ]; then
+        apt-get install -y --no-install-recommends libnvsdm=${DRIVER_VERSION}-1
+    fi
+}
 
 _update_package_cache() {
     if [ "${PACKAGE_TAG:-}" != "builtin" ]; then
         echo "Updating the package cache..."
-        apt-get -qq update
+        if ! apt-get -qq update; then
+            echo "ERROR: Failed to update package cache. "\
+                 "Ensure that the cluster can access the proper networks."
+            exit 1
+        fi
     fi
 }
 
@@ -29,6 +63,39 @@ _assert_nvswitch_system() {
     fi
     return 0
 }
+
+_assert_nvlink5_system() (
+    for dir in /sys/class/infiniband/*/device; do
+        # Define the path to the VPD file
+        vpd_file="$dir/vpd"
+
+        # Check if the VPD file exists
+        if [ -f "$vpd_file" ]; then
+            # Search for 'SW_MNG' in the VPD file
+            if grep -q "SW_MNG" "$vpd_file"; then
+                echo "Detected NVLink5+ system"
+                return 0
+            fi
+        fi
+    done
+    return 1
+)
+
+# These kernel modules are not loaded by default
+_load_ib_modules() {
+    apt-get install -y --no-install-recommends linux-modules-extra-${KERNEL_VERSION}
+    echo "Manually loading ib_umad and mlx5_ib"
+    modprobe ib_umad
+    modprobe mlx5_ib
+}
+
+_ensure_nvlink5_prerequisites() (
+    until  lsmod | grep mlx5_core > /dev/null 2>&1 && lsmod | grep ib_umad > /dev/null 2>&1;
+    do
+        echo "waiting for the mlx5_core and ib_umad kernel modules to be loaded"
+        sleep 10
+    done
+)
 
 # Check if mellanox devices are present
 _mellanox_devices_present() {
@@ -96,11 +163,30 @@ _get_module_params() {
     fi
 }
 
-# Load the kernel modules and start persistenced.
-_load_driver() {
+_create_module_params_conf() {
     echo "Parsing kernel module parameters..."
     _get_module_params
 
+    if [ ${#NVIDIA_MODULE_PARAMS[@]} -gt 0 ]; then
+        echo "Configuring nvidia module parameters in ${MODPROBE_CONFIG_DIR}/nvidia.conf"
+        echo "options nvidia ${NVIDIA_MODULE_PARAMS[@]}" > ${MODPROBE_CONFIG_DIR}/nvidia.conf
+    fi
+    if [ ${#NVIDIA_UVM_MODULE_PARAMS[@]} -gt 0 ]; then
+        echo "Configuring nvidia-uvm module parameters in ${MODPROBE_CONFIG_DIR}/nvidia-uvm.conf"
+        echo "options nvidia-uvm ${NVIDIA_UVM_MODULE_PARAMS[@]}" > ${MODPROBE_CONFIG_DIR}/nvidia-uvm.conf
+    fi
+    if [ ${#NVIDIA_MODESET_MODULE_PARAMS[@]} -gt 0 ]; then
+        echo "Configuring nvidia-modeset module parameters in ${MODPROBE_CONFIG_DIR}/nvidia-modeset.conf"
+        echo "options nvidia-modeset ${NVIDIA_MODESET_MODULE_PARAMS[@]}" > ${MODPROBE_CONFIG_DIR}/nvidia-modeset.conf
+    fi
+    if [ ${#NVIDIA_PEERMEM_MODULE_PARAMS[@]} -gt 0 ]; then
+        echo "Configuring nvidia-peermem module parameters in ${MODPROBE_CONFIG_DIR}/nvidia-peermem.conf"
+        echo "options nvidia-peermem ${NVIDIA_PEERMEM_MODULE_PARAMS[@]}" > ${MODPROBE_CONFIG_DIR}/nvidia-peermem.conf
+    fi
+}
+
+# Load the kernel modules and start persistenced.
+_load_driver() {
     local nv_fw_search_path="$RUN_DIR/driver/lib/firmware"
     local set_fw_path="true"
     local fw_path_config_file="/sys/module/firmware_class/parameters/path"
@@ -125,29 +211,61 @@ _load_driver() {
 
     echo "Loading NVIDIA driver kernel modules..."
     set -o xtrace +o nounset
-    modprobe nvidia "${NVIDIA_MODULE_PARAMS[@]}"
-    modprobe nvidia-uvm "${NVIDIA_UVM_MODULE_PARAMS[@]}"
-    modprobe nvidia-modeset "${NVIDIA_MODESET_MODULE_PARAMS[@]}"
+    modprobe nvidia
+    modprobe nvidia-uvm
+    modprobe nvidia-modeset
     set +o xtrace -o nounset
 
 
     if _gpu_direct_rdma_enabled; then
         echo "Loading NVIDIA Peer Memory kernel module..."
         set -o xtrace +o nounset
-        modprobe nvidia-peermem "${NVIDIA_PEERMEM_MODULE_PARAMS[@]}"
+        modprobe nvidia-peermem
         set +o xtrace -o nounset
     fi
 
     echo "Starting NVIDIA persistence daemon..."
     nvidia-persistenced --persistence-mode
 
-    DRIVER_VERSION=$(nvidia-smi -q | grep "Driver Version" | awk -F: '{print $2}' | xargs)
-    if _assert_nvswitch_system; then
-        echo "Installing NVIDIA fabric manager and libnvidia NSCQ packages..."
-        apt-get install -y --no-install-recommends \
-            nvidia-fabricmanager-${DRIVER_BRANCH}=${DRIVER_VERSION}-1 \
-            libnvidia-nscq-${DRIVER_BRANCH}=${DRIVER_VERSION}-1
+    if _is_grid_driver_required; then
+        # we need to start nvidia-gridd to get vGPU License for GRID driver
+        echo "Starting nvidia-gridd.."
+        LD_LIBRARY_PATH=/usr/lib/$(uname -m)-linux-gnu/nvidia/gridd nvidia-gridd
+    fi
 
+    # Load infiniband kernel modules on NVLink5+ systems
+    if lspci | grep -qiE 'mellanox|mlx5|connectx'; then
+        _load_ib_modules
+    fi
+
+    if _assert_nvlink5_system; then
+        _ensure_nvlink5_prerequisites || return 1
+
+        echo "Installing NVIDIA fabric manager, libnvsdm and nvlsm packages..."
+
+        nvlink5_pkgs_install
+        fabricmanager_install
+        nvsdm_install
+        imex_install
+
+        echo "Starting NVIDIA fabric manager daemon for NVLink5+..."
+
+        fm_config_file=/usr/share/nvidia/nvswitch/fabricmanager.cfg
+        fm_pid_file=/var/run/nvidia-fabricmanager/nv-fabricmanager.pid
+        nvlsm_config_file=/usr/share/nvidia/nvlsm/nvlsm.conf
+        nvlsm_pid_file=/var/run/nvidia-fabricmanager/nvlsm.pid
+        /usr/bin/nvidia-fabricmanager-start.sh --mode start \
+                                               --fm-config-file $fm_config_file \
+                                               --fm-pid-file $fm_pid_file \
+                                               --nvlsm-config-file $nvlsm_config_file \
+                                               --nvlsm-pid-file $nvlsm_pid_file
+
+    # If not a NVLink5+ switch, check for the presence of NVLink4 (or below) switches
+    elif _assert_nvswitch_system; then
+        echo "Installing NVIDIA fabric manager and libnvidia NSCQ packages..."
+        fabricmanager_install
+        nscq_install
+        imex_install
         echo "Starting NVIDIA fabric manager daemon..."
         nv-fabricmanager -c /usr/share/nvidia/nvswitch/fabricmanager.cfg
     fi
@@ -164,8 +282,23 @@ _unload_driver() {
     local nvidia_modeset_refs=0
     local nvidia_peermem_refs=0
 
-    echo "Stopping NVIDIA persistence daemon..."
+    if [ -f /var/run/nvidia-gridd/nvidia-gridd.pid ]; then
+        echo "Stopping NVIDIA grid daemon..."
+        local pid=$(< /var/run/nvidia-gridd/nvidia-gridd.pid)
+
+        kill -SIGTERM "${pid}"
+        for i in $(seq 1 10); do
+            kill -0 "${pid}" 2> /dev/null || break
+            sleep 0.1
+        done
+        if [ $i -eq 10 ]; then
+            echo "Could not stop NVIDIA Grid daemon" >&2
+            return 1
+        fi
+    fi
+
     if [ -f /var/run/nvidia-persistenced/nvidia-persistenced.pid ]; then
+        echo "Stopping NVIDIA persistence daemon..."
         local pid=$(< /var/run/nvidia-persistenced/nvidia-persistenced.pid)
 
         kill -SIGTERM "${pid}"
@@ -190,6 +323,21 @@ _unload_driver() {
         done
         if [ $i -eq 50 ]; then
             echo "Could not stop NVIDIA fabric manager daemon" >&2
+            return 1
+        fi
+    fi
+
+    if [ -f /var/run/nvidia-fabricmanager/nvlsm.pid ]; then
+        echo "Stopping NVLink Subnet Manager daemon..."
+        local pid=$(< /var/run/nvidia-fabricmanager/nvlsm.pid)
+
+        kill -SIGTERM "${pid}"
+        for i in $(seq 1 50); do
+            kill -0 "${pid}" 2> /dev/null || break
+            sleep 0.1
+        done
+        if [ $i -eq 50 ]; then
+            echo "Could not stop NVLink Subnet Manager daemon" >&2
             return 1
         fi
     fi
@@ -232,30 +380,67 @@ _unload_driver() {
     return 0
 }
 
-# Link and install the kernel modules from a precompiled packages
-_install_driver() {
-    # Install necessary userspace, fabric manager and libnvidia-nscq packages
-    apt-get install -y --no-install-recommends nvidia-driver-${DRIVER_BRANCH}-server
+_resolve_kernel_type_from_driver_branch() {
+  [[ "${DRIVER_BRANCH}" -lt 560 ]] && KERNEL_TYPE=kernel || KERNEL_TYPE=kernel-open
+}
 
-    # Uninstall unnecessary packages installed as a part of the nvidia-driver-${DRIVER_BRANCH}-server package
-    apt-get purge -y \
-        libnvidia-egl-wayland1 \
-        nvidia-dkms-${DRIVER_BRANCH}-server \
-        nvidia-kernel-source-${DRIVER_BRANCH}-server \
-        xserver-xorg-video-nvidia-${DRIVER_BRANCH}-server
+# _resolve_kernel_type determines which kernel module type, open or proprietary, to install.
+# This function assumes that the nvidia-installer binary is in the PATH, so this function
+# should only be invoked after the userspace driver components have been installed.
+#
+# KERNEL_MODULE_TYPE is the frontend interface that users can use to configure which module
+# to install. Valid values for KERNEL_MODULE_TYPE are 'auto' (default), 'open', and 'proprietary'.
+# When 'auto' is configured, we use the nvidia-installer to recommend the module type to install.
+_resolve_kernel_type() {
+  if [ "${KERNEL_MODULE_TYPE}" == "proprietary" ]; then
+    KERNEL_TYPE=kernel
+  elif [ "${KERNEL_MODULE_TYPE}" == "open" ]; then
+    KERNEL_TYPE=kernel-open
+  elif [ "${KERNEL_MODULE_TYPE}" == "auto" ]; then
+    kernel_module_type=$(nvidia-installer --print-recommended-kernel-module-type 2> /dev/null)
+    if [ $? -ne 0 ]; then
+      echo "failed to retrieve the recommended kernel module type from nvidia-installer, falling back to using the driver branch"
+      _resolve_kernel_type_from_driver_branch
+      return 0
+    fi
+    [[ "${kernel_module_type}" == "open" ]] && KERNEL_TYPE=kernel-open || KERNEL_TYPE=kernel
+  else
+    echo "invalid value for the KERNEL_MODULE_TYPE variable: ${KERNEL_MODULE_TYPE}"
+    return 1
+  fi
+}
+
+# Link and install the kernel modules from a precompiled packages
+_install_precompiled_driver() {
+    # Install necessary driver userspace packages
+    apt-get install -y --no-install-recommends \
+        nvidia-utils-${DRIVER_BRANCH}-server=${FULL_DRIVER_VERSION} \
+        nvidia-headless-no-dkms-${DRIVER_BRANCH}-server=${FULL_DRIVER_VERSION} \
+        libnvidia-decode-${DRIVER_BRANCH}-server=${FULL_DRIVER_VERSION} \
+        libnvidia-extra-${DRIVER_BRANCH}-server=${FULL_DRIVER_VERSION} \
+        libnvidia-encode-${DRIVER_BRANCH}-server=${FULL_DRIVER_VERSION} \
+        libnvidia-fbc1-${DRIVER_BRANCH}-server=${FULL_DRIVER_VERSION}
 
     # Now install the precompiled kernel module packages signed by Canonical
-    if [ "$OPEN_KERNEL_MODULES_ENABLED" = true ]; then
+    if [ "$KERNEL_TYPE" = "kernel-open" ]; then
         echo "Installing Open NVIDIA driver kernel modules..."
         apt-get install --no-install-recommends -y \
-            linux-signatures-nvidia-${KERNEL_VERSION} \
-            linux-modules-nvidia-${DRIVER_BRANCH}-server-open-${KERNEL_VERSION}
+            linux-signatures-nvidia-${KERNEL_VERSION}=${MODULES_VERSION} \
+            linux-modules-nvidia-${DRIVER_BRANCH}-server-open-${KERNEL_VERSION}=${MODULES_VERSION}
     else
         echo "Installing Closed NVIDIA driver kernel modules..."
         apt-get install --no-install-recommends -y \
-            linux-objects-nvidia-${DRIVER_BRANCH}-server-${KERNEL_VERSION} \
-            linux-signatures-nvidia-${KERNEL_VERSION} \
-            linux-modules-nvidia-${DRIVER_BRANCH}-server-${KERNEL_VERSION}
+            linux-objects-nvidia-${DRIVER_BRANCH}-server-${KERNEL_VERSION}=${MODULES_VERSION} \
+            linux-signatures-nvidia-${KERNEL_VERSION}=${MODULES_VERSION} \
+            linux-modules-nvidia-${DRIVER_BRANCH}-server-${KERNEL_VERSION}=${MODULES_VERSION}
+    fi
+}
+
+_install_driver() {
+    if _is_grid_driver_required; then
+        _install_grid_driver
+    else
+        _install_precompiled_driver
     fi
 }
 
@@ -277,6 +462,9 @@ _unmount_rootfs() {
 }
 
 init() {
+    # Determine the kernel module type
+    _resolve_kernel_type || exit 1
+
     echo -e "\n========== NVIDIA Software Installer ==========\n"
     echo -e "Starting installation of NVIDIA driver branch ${DRIVER_BRANCH} for Linux kernel version ${KERNEL_VERSION}\n"
 
@@ -293,6 +481,7 @@ init() {
     _unload_driver || exit 1
     _unmount_rootfs
 
+    _create_module_params_conf
     _install_driver
     _load_driver || exit 1
     _mount_rootfs
