[local] fix(nvidia-driver): add nvidia-imex

diff --git a/ubuntu22.04/precompiled/nvidia-driver b/ubuntu22.04/precompiled/nvidia-driver
--- a/ubuntu22.04/precompiled/nvidia-driver
+++ b/ubuntu22.04/precompiled/nvidia-driver
@@ -7,6 +7,7 @@ KERNEL_VERSION=$(uname -r)
 RUN_DIR=/run/nvidia
 PID_FILE=${RUN_DIR}/${0##*/}.pid
 DRIVER_BRANCH=${DRIVER_BRANCH:?"Missing driver branch"}
+DRIVER_VERSION=${DRIVER_VERSION:?"Missing driver version"}
 MODULES_VERSION=${MODULES_VERSION:?"Missing modules version"}
 FULL_DRIVER_VERSION=${FULL_DRIVER_VERSION:?"Missing full driver version"}
 GPU_DIRECT_RDMA_ENABLED="${GPU_DIRECT_RDMA_ENABLED:-false}"
@@ -15,12 +16,43 @@ NVIDIA_MODULE_PARAMS=()
 NVIDIA_UVM_MODULE_PARAMS=()
 NVIDIA_MODESET_MODULE_PARAMS=()
 NVIDIA_PEERMEM_MODULE_PARAMS=()
+TARGETARCH=${TARGETARCH:?"Missing TARGETARCH env"}
 KERNEL_MODULE_TYPE=${KERNEL_MODULE_TYPE:-auto}
+MODPROBE_CONFIG_DIR="/etc/modprobe.d"
+
+fabricmanager_install() {
+    apt-get install -y --no-install-recommends --no-download nvidia-fabricmanager-${DRIVER_BRANCH}=${FULL_DRIVER_VERSION}
+}
+
+nscq_install() {
+    apt-get install -y --no-install-recommends --no-download libnvidia-nscq-${DRIVER_BRANCH}=${FULL_DRIVER_VERSION}
+}
+
+imex_install() {
+    apt-get install -y --no-install-recommends --no-download nvidia-imex-${DRIVER_BRANCH}=${FULL_DRIVER_VERSION}
+}
+
+nvlink5_pkgs_install() {
+    apt-get install -y --no-install-recommends --no-download \
+        infiniband-diags \
+        nvlsm
+}
+
+# libnvsdm packages are not available for arm64
+nvsdm_install() {
+    if [ "$TARGETARCH" = "amd64" ]; then
+        apt-get install -y --no-install-recommends --no-download libnvsdm=${DRIVER_VERSION}-1
+    fi
+}
 
 _update_package_cache() {
     if [ "${PACKAGE_TAG:-}" != "builtin" ]; then
         echo "Updating the package cache..."
-        apt-get -qq update
+        if ! apt-get -qq update; then
+            echo "ERROR: Failed to update package cache. "\
+                 "Ensure that the cluster can access the proper networks."
+            exit 1
+        fi
     fi
 }
 
@@ -123,11 +155,30 @@ _get_module_params() {
     fi
 }
 
-# Load the kernel modules and start persistenced.
-_load_driver() {
+_create_module_params_conf() {
     echo "Parsing kernel module parameters..."
     _get_module_params
 
+    if [ ${#NVIDIA_MODULE_PARAMS[@]} -gt 0 ]; then
+        echo "Configuring nvidia module parameters in ${MODPROBE_CONFIG_DIR}/nvidia.conf"
+        echo "options nvidia ${NVIDIA_MODULE_PARAMS[@]}" > ${MODPROBE_CONFIG_DIR}/nvidia.conf
+    fi
+    if [ ${#NVIDIA_UVM_MODULE_PARAMS[@]} -gt 0 ]; then
+        echo "Configuring nvidia-uvm module parameters in ${MODPROBE_CONFIG_DIR}/nvidia-uvm.conf"
+        echo "options nvidia-uvm ${NVIDIA_UVM_MODULE_PARAMS[@]}" > ${MODPROBE_CONFIG_DIR}/nvidia-uvm.conf
+    fi
+    if [ ${#NVIDIA_MODESET_MODULE_PARAMS[@]} -gt 0 ]; then
+        echo "Configuring nvidia-modeset module parameters in ${MODPROBE_CONFIG_DIR}/nvidia-modeset.conf"
+        echo "options nvidia-modeset ${NVIDIA_MODESET_MODULE_PARAMS[@]}" > ${MODPROBE_CONFIG_DIR}/nvidia-modeset.conf
+    fi
+    if [ ${#NVIDIA_PEERMEM_MODULE_PARAMS[@]} -gt 0 ]; then
+        echo "Configuring nvidia-peermem module parameters in ${MODPROBE_CONFIG_DIR}/nvidia-peermem.conf"
+        echo "options nvidia-peermem ${NVIDIA_PEERMEM_MODULE_PARAMS[@]}" > ${MODPROBE_CONFIG_DIR}/nvidia-peermem.conf
+    fi
+}
+
+# Load the kernel modules and start persistenced.
+_load_driver() {
     local nv_fw_search_path="$RUN_DIR/driver/lib/firmware"
     local set_fw_path="true"
     local fw_path_config_file="/sys/module/firmware_class/parameters/path"
@@ -152,16 +203,16 @@ _load_driver() {
 
     echo "Loading NVIDIA driver kernel modules..."
     set -o xtrace +o nounset
-    modprobe nvidia "${NVIDIA_MODULE_PARAMS[@]}"
-    modprobe nvidia-uvm "${NVIDIA_UVM_MODULE_PARAMS[@]}"
-    modprobe nvidia-modeset "${NVIDIA_MODESET_MODULE_PARAMS[@]}"
+    modprobe nvidia
+    modprobe nvidia-uvm
+    modprobe nvidia-modeset
     set +o xtrace -o nounset
 
 
     if _gpu_direct_rdma_enabled; then
         echo "Loading NVIDIA Peer Memory kernel module..."
         set -o xtrace +o nounset
-        modprobe nvidia-peermem "${NVIDIA_PEERMEM_MODULE_PARAMS[@]}"
+        modprobe nvidia-peermem
         set +o xtrace -o nounset
     fi
 
@@ -172,11 +223,11 @@ _load_driver() {
         _ensure_nvlink5_prerequisites || return 1
 
         echo "Installing NVIDIA fabric manager, libnvsdm and nvlsm packages..."
-        apt-get install -y --no-install-recommends --no-download \
-            infiniband-diags \
-            nvidia-fabricmanager-${DRIVER_BRANCH}=${FULL_DRIVER_VERSION} \
-            libnvsdm=${DRIVER_VERSION}-1 \
-            nvlsm
+
+        nvlink5_pkgs_install
+        fabricmanager_install
+        nvsdm_install
+        imex_install
 
         echo "Starting NVIDIA fabric manager daemon for NVLink5+..."
 
@@ -193,10 +244,9 @@ _load_driver() {
     # If not a NVLink5+ switch, check for the presence of NVLink4 (or below) switches
     elif _assert_nvswitch_system; then
         echo "Installing NVIDIA fabric manager and libnvidia NSCQ packages..."
-        apt-get install -y --no-install-recommends --no-download \
-            nvidia-fabricmanager-${DRIVER_BRANCH}=${FULL_DRIVER_VERSION} \
-            libnvidia-nscq-${DRIVER_BRANCH}=${FULL_DRIVER_VERSION}
-
+        fabricmanager_install
+        nscq_install
+        imex_install
         echo "Starting NVIDIA fabric manager daemon..."
         nv-fabricmanager -c /usr/share/nvidia/nvswitch/fabricmanager.cfg
     fi
@@ -389,6 +439,7 @@ init() {
     _unload_driver || exit 1
     _unmount_rootfs
 
+    _create_module_params_conf
     _install_driver
     _load_driver || exit 1
     _mount_rootfs
